version: "3.8"
name: skyback
services:
  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_DATABASE=skyexplorer
    ports:
      - '80:80'
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  backend:
    container_name: backend
    build: ./app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/skyexplorer
      - PORT=4000
      - ACCESS_TOKEN_SECRET=cestvraimentsecret
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    links:
      - mongodb

volumes:
  dbdata6: